### ISSUE TITLE
Update in the remote control the control modification in control surface from Score 

### ISSUE THREAD

**Issue by Toine-ddt** [ossia/qml-remote#11]
@jcelerier

**Comment by jcelerier** [comment]
where is this in the QML code ?

**Comment by Toine-ddt** [comment]
https://github.com/iscore-pfa/qml-remote/blob/31b0566963936e0674409785a579010678f5466e/src/ScoreControlSurfaces.qml#L82

**Comment by jcelerier** [comment]
so, I don't know the code but at that point what should happen should be : 

- find the UI object which maps to the controlsurface id given in the message (`m.Path`)
- find the control through the given id (`m.Control`) 
- the UI controls should have a `value` property or something like that which can be set 

All in all I guess this needs two levels of maps to work ? Maybe you can just use JS objects to do the path <-> qml ui object mapping, or have a function that does it
