### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by jcelerier** [ossia/qml-remote#56]
There starts to be quite a lot of code.
I think that it would be beneficial to have some documentation : for instance a few .md files that describe the overall architecture (it can be based on the existing report !) and some documentation blocks in source files for the most important classes.

In the doc to make it useful, describe the overall design (how classes fit together, etc) - that's the most helpful thing to have

**Comment by Toine-ddt** [comment]
I will work on it !

**Comment by jcelerier** [comment]
my recommendation is - don't spend time explicitely on it, but every time you work on a file, if the file is not documented spend a minute writing a couple lines of text about what this file is doing, what is it for, where it is used, etc..

**Comment by Toine-ddt** [comment]
ok
